version: '3.9'
services:
  app:
    container_name: golang_container
    build: 
      context: .
      dockerfile: Dockerfile.multistage
    ports:
      - 3000:3000
    networks:
      - learning
  redis-db:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    container_name: redis-db
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - learning

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge