# syntax=docker/dockerfile:1

## Build
FROM golang:1.16-buster AS build

WORKDIR /app

COPY . .

RUN go mod download
RUN go build ./cmd/banm-gpt-tg-bot

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /app/banm-gpt-tg-bot /banm-gpt-tg-bot
COPY .env /

EXPOSE 3000

USER nonroot:nonroot

ENTRYPOINT ["/banm-gpt-tg-bot"]